# Generated by Django 2.2.6 on 2019-10-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clients',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='first_time_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
