# Generated by Django 2.2.6 on 2019-11-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
