# Generated by Django 2.2.6 on 2019-11-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_doctor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
