# Generated by Django 2.2.6 on 2019-11-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_auto_20191113_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField(default=456)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verfied', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_time_login', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(blank=True, default='app/images/doc.png', upload_to='medico_experts/images/')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('aboutme', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('contactno', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=70)),
                ('terms', models.BooleanField(default=False)),
                ('hospital_affiliations', models.CharField(blank=True, max_length=50)),
                ('medical_school', models.CharField(blank=True, max_length=100)),
                ('residency', models.CharField(blank=True, max_length=100)),
                ('certifications', models.CharField(blank=True, max_length=100)),
                ('internship', models.CharField(blank=True, max_length=100)),
                ('specialties', models.CharField(blank=True, max_length=500)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('task_notification', models.BooleanField(default=True)),
                ('friend_notification', models.BooleanField(default=True)),
                ('experience', models.CharField(blank=True, default='None', max_length=50)),
                ('awards', models.CharField(blank=True, default='None', max_length=50)),
                ('clients', models.CharField(blank=True, default='None', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
