# Generated by Django 2.2.6 on 2019-11-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
